# -*- coding: utf-8 -*-
"""Proyecto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T7PsWq_fiI5d_LezHXF1ZJxOYUCdFrtW
"""

# Librerias

import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# mostrar la informacion

df = pd.read_csv("steam_reviews.csv")
df.head()

df = df.dropna()

df["review"] = df["review"].str.lower()

X = df["review"]
y = df["recommendation"]  # 1 positivo, 0 negativo

pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(
        lowercase=True,
        stop_words="english",
        max_df=0.9
    )),
    ("svm", LinearSVC())
])

TfidfVectorizer(
    ngram_range=(1,2),
    stop_words="english"
)

# dividir los datos
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Definición del pipeline
pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(
        lowercase=True,
        stop_words="english",
        max_df=0.9
    )),
    ("svm", LinearSVC())
])

# Entrenando el pipeline con X_train (texto original) y y_train
pipeline.fit(X_train, y_train)

#evaluando el modelo
y_pred = pipeline.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

sarcastic_reviews = [
    "Yeah amazing game",
    "Best game ever (refund requested)",
    "Balatreate 🤙",
    "Great experience, would uninstall again"
]

predictions = pipeline.predict(sarcastic_reviews)

for r, p in zip(sarcastic_reviews, predictions):
    print(f"{p} → {r}")